server:
  port: 8084

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

eureka:
  client:
    enabled: false